### ISSUE TITLE
Home :: Block 1:: Tableta

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#11]
Mejorar columna derecha

Igual darle una revisada a los otros bloques, se pueden hacer pequeño ajustes para mejorar la presentación
![screen shot 2016-01-19 at 7 38 19 pm](https://cloud.githubusercontent.com/assets/7799215/12437545/528aa03e-bee4-11e5-8ca2-cf263813f860.png)

**Comment by ale-romo** [comment]
done
