### ISSUE TITLE
Home :: Cellphone

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#12]
Hacer que todos los elementos de la sección tengan el mismo "padding-left"
![screen shot 2016-01-19 at 7 40 03 pm](https://cloud.githubusercontent.com/assets/7799215/12437561/91228aa0-bee4-11e5-9f5f-09390b7b00ba.png)

**Comment by ale-romo** [comment]
done, pero causa que los íconos morados no quepan en un renglón, mi opinión es que está bien que se quede de esa manera.
