### ISSUE TITLE
tablet :: home :: banner :: header

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#43]
se encima el tel  con inicio
![screen shot 2016-02-02 at 7 49 24 pm](https://cloud.githubusercontent.com/assets/7799215/12770448/2397d5b4-c9e6-11e5-94ca-ddcb505b2045.png)

**Comment by ale-romo** [comment]
fixed

**Comment by garciadiazjaime** [comment]
este sigue pasando .. en el menux fixed no sucede, pero en el menu inicial si
