### ISSUE TITLE
tablet :: home :: block4

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#45]
el contenido esta muy pegado a la derecha, tendria que haber un padding/margin right
![screen shot 2016-02-02 at 7 51 30 pm](https://cloud.githubusercontent.com/assets/7799215/12770485/785fa2de-c9e6-11e5-9317-cdb8ef98ecbf.png)

**Comment by ale-romo** [comment]
listo
