### ISSUE TITLE
tablet :: home :: block5

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#46]
'de' queda en una sola linea, vamos a quitarle el que este en 2 atomos, que sea solo uno para que el texto se acomo solito, ver si podemos hacer que se vea como el diseno en cuanto al salto de linea
![screen shot 2016-02-02 at 7 53 34 pm](https://cloud.githubusercontent.com/assets/7799215/12770521/d23207ac-c9e6-11e5-9437-c1fd1a691da8.png)

**Comment by ale-romo** [comment]
fixed, pero se la pelan en full size.

**Comment by garciadiazjaime** [comment]
ta bién, ese será el flujo natural del texto
