### ISSUE TITLE
tablet :: layout :: footer

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#47]
tijuana al ser de dos renglones deja de estar alineado en X con San Diego y Servicios, haciendo que el telefono tambien este desalineado
![screen shot 2016-02-02 at 7 55 16 pm](https://cloud.githubusercontent.com/assets/7799215/12770563/02933470-c9e7-11e5-9c07-68365a8268e7.png)

**Comment by ale-romo** [comment]
listo
