### ISSUE TITLE
nosotros :: bloque 5

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#49]
bajar un poco el cuadro amarillo para que el final coincida con el final del bloque rojo (izquierda)
![screen shot 2016-02-02 at 7 57 31 pm](https://cloud.githubusercontent.com/assets/7799215/12770604/52da9144-c9e7-11e5-9cfd-d483546b4626.png)

**Comment by ale-romo** [comment]
done, aunque solo funciona en resoluciones => a 1024, más angosto se descuadra.

**Comment by garciadiazjaime** [comment]
simón, así está bien ... nuestro compromiso desktop >= 1024, ipad y ipohne5 .. pero aja este solo aplica para desktop

**Comment by ale-romo** [comment]
ps aja, en ipad no va a salir cuadrado.

**Comment by garciadiazjaime** [comment]
está bien
