### ISSUE TITLE
servicios :: inner

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#50]
va un font-size más pequeño  (bold debería ser 16px...)
![screen shot 2016-02-02 at 8 10 36 pm](https://cloud.githubusercontent.com/assets/7799215/12770794/1fc45900-c9e9-11e5-81e4-dc292327c7e9.png)

**Comment by ale-romo** [comment]
los font size están igualitos al docu:
Todas aquellas (21px bold)
U.S. Department (16px bold)
También conocida (16px)

**Comment by garciadiazjaime** [comment]
arre
