### ISSUE TITLE
consultoria :: bullets

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#51]
La columna izquierda (número) va más chica, el texto debería tener más espacio (ancho)
![screen shot 2016-02-02 at 8 13 26 pm](https://cloud.githubusercontent.com/assets/7799215/12770840/87b355ac-c9e9-11e5-9dc4-c542fb2e6c86.png)

**Comment by ale-romo** [comment]
listo
