### ISSUE TITLE
tableta :: servicios :: submenú

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#52]
muy pegado a la derecha
![screen shot 2016-02-02 at 8 14 52 pm](https://cloud.githubusercontent.com/assets/7799215/12770856/af6743ba-c9e9-11e5-9a1a-7ef67f0aa8e7.png)

PD. En general el contenido de la sección está muy pegado a al derecha, ver si le podemos jalar un poco a izq

**Comment by ale-romo** [comment]
fixed
