### ISSUE TITLE
Permisos :: otros permisos

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-interbrokers#54]
http://127.0.0.1:3030/servicios/permisos/permisos-otros

botón va rojo
![screen shot 2016-02-02 at 8 19 40 pm](https://cloud.githubusercontent.com/assets/7799215/12770922/609d764a-c9ea-11e5-9352-7846dcd17ad6.png)

**Comment by ale-romo** [comment]
done
